# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/wallpaper/download.jpg'

# Special
background='#170f11'
foreground='#c0b0c5'
cursor='#c0b0c5'

# Colors
color0='#170f11'
color1='#AC583B'
color2='#A26857'
color3='#BF8A6D'
color4='#D8936C'
color5='#3E44A3'
color6='#685788'
color7='#c0b0c5'
color8='#867b89'
color9='#AC583B'
color10='#A26857'
color11='#BF8A6D'
color12='#D8936C'
color13='#3E44A3'
color14='#685788'
color15='#c0b0c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
