--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/wallpaper/download.jpg"

-- Special
background="#170f11"
foreground="#c0b0c5"
cursor="#c0b0c5"

-- Colors
color0="#170f11"
color1="#AC583B"
color2="#A26857"
color3="#BF8A6D"
color4="#D8936C"
color5="#3E44A3"
color6="#685788"
color7="#c0b0c5"
color8="#867b89"
color9="#AC583B"
color10="#A26857"
color11="#BF8A6D"
color12="#D8936C"
color13="#3E44A3"
color14="#685788"
color15="#c0b0c5"
