#! /bin/sh

$HOME/.config/polybar/launch.sh &
nm-applet &
flameshot &
premid &
picom -f &
lxpolkit &
xsetroot -cursor_name left_ptr &
nitrogen --restore


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12
bspc config focused_border_color \#E1B7CA
bspc config normal_border_color \#DEAFB1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
