# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/wallpaper/__kamisato_ayaka_genshin_impact_drawn_by_kkk_dami__4090d5e34e0ca5aacce9ed96394eb6f8.png'

# Special
background='#2d2228'
foreground='#f2e0ed'
cursor='#f2e0ed'

# Colors
color0='#2d2228'
color1='#D2A5AD'
color2='#ABA7CA'
color3='#E1B2D3'
color4='#C6C7D2'
color5='#D4CBD4'
color6='#E3D4D7'
color7='#f2e0ed'
color8='#a99ca5'
color9='#D2A5AD'
color10='#ABA7CA'
color11='#E1B2D3'
color12='#C6C7D2'
color13='#D4CBD4'
color14='#E3D4D7'
color15='#f2e0ed'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
