# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/wallpaper/cropped-2560-1440-1173532 (1).jpg'

# Special
background='#19101e'
foreground='#ebe0e1'
cursor='#ebe0e1'

# Colors
color0='#19101e'
color1='#96688C'
color2='#CD7B92'
color3='#B092A1'
color4='#CFA7B1'
color5='#D8BAC4'
color6='#E0CED2'
color7='#ebe0e1'
color8='#a49c9d'
color9='#96688C'
color10='#CD7B92'
color11='#B092A1'
color12='#CFA7B1'
color13='#D8BAC4'
color14='#E0CED2'
color15='#ebe0e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
