--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/wallpaper/cropped-2560-1440-1173532 (1).jpg"

-- Special
background="#19101e"
foreground="#ebe0e1"
cursor="#ebe0e1"

-- Colors
color0="#19101e"
color1="#96688C"
color2="#CD7B92"
color3="#B092A1"
color4="#CFA7B1"
color5="#D8BAC4"
color6="#E0CED2"
color7="#ebe0e1"
color8="#a49c9d"
color9="#96688C"
color10="#CD7B92"
color11="#B092A1"
color12="#CFA7B1"
color13="#D8BAC4"
color14="#E0CED2"
color15="#ebe0e1"
