# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/shit/wall/cropped-2560-1440-1172301.png'

# Special
background='#161319'
foreground='#e7cddc'
cursor='#e7cddc'

# Colors
color0='#161319'
color1='#6C5891'
color2='#614FA0'
color3='#976E99'
color4='#BC74A8'
color5='#BDA3AD'
color6='#D89DAC'
color7='#e7cddc'
color8='#a18f9a'
color9='#6C5891'
color10='#614FA0'
color11='#976E99'
color12='#BC74A8'
color13='#BDA3AD'
color14='#D89DAC'
color15='#e7cddc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
