--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/shit/wall/cropped-2560-1440-1172301.png"

-- Special
background="#161319"
foreground="#e7cddc"
cursor="#e7cddc"

-- Colors
color0="#161319"
color1="#6C5891"
color2="#614FA0"
color3="#976E99"
color4="#BC74A8"
color5="#BDA3AD"
color6="#D89DAC"
color7="#e7cddc"
color8="#a18f9a"
color9="#6C5891"
color10="#614FA0"
color11="#976E99"
color12="#BC74A8"
color13="#BDA3AD"
color14="#D89DAC"
color15="#e7cddc"
