# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/wallpaper/hu-tao-ghost-genshin-impact-2k-wallpaper-2560x1440-uhdpaper.com-265.1_a.jpg'

# Special
background='#160d0d'
foreground='#ecdfd0'
cursor='#ecdfd0'

# Colors
color0='#160d0d'
color1='#B05943'
color2='#9E6A59'
color3='#BC916F'
color4='#E49970'
color5='#65648A'
color6='#D8AA95'
color7='#ecdfd0'
color8='#a59c91'
color9='#B05943'
color10='#9E6A59'
color11='#BC916F'
color12='#E49970'
color13='#65648A'
color14='#D8AA95'
color15='#ecdfd0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
