--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/wallpaper/hu-tao-ghost-genshin-impact-2k-wallpaper-2560x1440-uhdpaper.com-265.1_a.jpg"

-- Special
background="#160d0d"
foreground="#ecdfd0"
cursor="#ecdfd0"

-- Colors
color0="#160d0d"
color1="#B05943"
color2="#9E6A59"
color3="#BC916F"
color4="#E49970"
color5="#65648A"
color6="#D8AA95"
color7="#ecdfd0"
color8="#a59c91"
color9="#B05943"
color10="#9E6A59"
color11="#BC916F"
color12="#E49970"
color13="#65648A"
color14="#D8AA95"
color15="#ecdfd0"
