# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/wallpaper/ayaka_lumine_with_mask_4k_hd_genshin_impact-2560x1440.jpg'

# Special
background='#191319'
foreground='#e7e7e7'
cursor='#e7e7e7'

# Colors
color0='#191319'
color1='#DEA061'
color2='#4C5896'
color3='#AAA19F'
color4='#8581AA'
color5='#F0DBA3'
color6='#C2B5C1'
color7='#e7e7e7'
color8='#a1a1a1'
color9='#DEA061'
color10='#4C5896'
color11='#AAA19F'
color12='#8581AA'
color13='#F0DBA3'
color14='#C2B5C1'
color15='#e7e7e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
