--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/wallpaper/ayaka_lumine_with_mask_4k_hd_genshin_impact-2560x1440.jpg"

-- Special
background="#191319"
foreground="#e7e7e7"
cursor="#e7e7e7"

-- Colors
color0="#191319"
color1="#DEA061"
color2="#4C5896"
color3="#AAA19F"
color4="#8581AA"
color5="#F0DBA3"
color6="#C2B5C1"
color7="#e7e7e7"
color8="#a1a1a1"
color9="#DEA061"
color10="#4C5896"
color11="#AAA19F"
color12="#8581AA"
color13="#F0DBA3"
color14="#C2B5C1"
color15="#e7e7e7"
