--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/shit/wallpaper/mruz3mpo30h81 (2).jpg"

-- Special
background="#211214"
foreground="#dddbea"
cursor="#dddbea"

-- Colors
color0="#211214"
color1="#D86766"
color2="#C3837E"
color3="#BEA6BF"
color4="#E09C9E"
color5="#C8BBDA"
color6="#E4D3DF"
color7="#dddbea"
color8="#9a99a3"
color9="#D86766"
color10="#C3837E"
color11="#BEA6BF"
color12="#E09C9E"
color13="#C8BBDA"
color14="#E4D3DF"
color15="#dddbea"
