# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/shit/wallpaper/mruz3mpo30h81 (2).jpg'

# Special
background='#211214'
foreground='#dddbea'
cursor='#dddbea'

# Colors
color0='#211214'
color1='#D86766'
color2='#C3837E'
color3='#BEA6BF'
color4='#E09C9E'
color5='#C8BBDA'
color6='#E4D3DF'
color7='#dddbea'
color8='#9a99a3'
color9='#D86766'
color10='#C3837E'
color11='#BEA6BF'
color12='#E09C9E'
color13='#C8BBDA'
color14='#E4D3DF'
color15='#dddbea'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
