--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/wallpaper/__kamisato_ayaka_genshin_impact_drawn_by_rayleigh_scale__bc4fe587af1a0ce8231d7a99d53dda5e.jpg"

-- Special
background="#0b0708"
foreground="#efdfc0"
cursor="#efdfc0"

-- Colors
color0="#0b0708"
color1="#D2A077"
color2="#58548D"
color3="#916F90"
color4="#7C8198"
color5="#DBAE90"
color6="#D5BFBF"
color7="#efdfc0"
color8="#a79c86"
color9="#D2A077"
color10="#58548D"
color11="#916F90"
color12="#7C8198"
color13="#DBAE90"
color14="#D5BFBF"
color15="#efdfc0"
