--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alice/wallpaper/ganyu-kamisato-ayaka-genshin-impact-kimono-anime-games-anime.jpeg"

-- Special
background="#15070f"
foreground="#e9e1e4"
cursor="#e9e1e4"

-- Colors
color0="#15070f"
color1="#A67491"
color2="#A88C97"
color3="#A293A7"
color4="#E3A3A8"
color5="#9FABCF"
color6="#D7C1C9"
color7="#e9e1e4"
color8="#a39d9f"
color9="#A67491"
color10="#A88C97"
color11="#A293A7"
color12="#E3A3A8"
color13="#9FABCF"
color14="#D7C1C9"
color15="#e9e1e4"
