# Shell variables
# Generated by 'wal'
wallpaper='/home/alice/wallpaper/ganyu-kamisato-ayaka-genshin-impact-kimono-anime-games-anime.jpeg'

# Special
background='#15070f'
foreground='#e9e1e4'
cursor='#e9e1e4'

# Colors
color0='#15070f'
color1='#A67491'
color2='#A88C97'
color3='#A293A7'
color4='#E3A3A8'
color5='#9FABCF'
color6='#D7C1C9'
color7='#e9e1e4'
color8='#a39d9f'
color9='#A67491'
color10='#A88C97'
color11='#A293A7'
color12='#E3A3A8'
color13='#9FABCF'
color14='#D7C1C9'
color15='#e9e1e4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
